[project]
name = "newt-starter-yam"
version = "0.1.0"
requires-python = ">=3.11"
dependencies = [
    "newt @ git+ssh://git@github.com/new-theory-research/newt-python.git@e73187e0a59c24d5c2c94cea3461ac4cec8aca1d",
    "numpy>=1.26",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.metadata]
allow-direct-references = true

[tool.hatch.build.targets.wheel]
packages = ["."]
